apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mjf948c6n-nodejs 
  janus-idp.io/tekton: mjf948c6n-nodejs
  backstage.io/kubernetes-id: mjf948c6n-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mjf948c6n-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  