apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: mjf948c6n-nodejs-gitops
  description: This is GitOps manifest for mjf948c6n-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: mjf948c6n-nodejs
    backstage.io/kubernetes-id: mjf948c6n-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: mjf948c6n-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:mjf948c6n-nodejs
